package com.edwardpang.escmanager;

public enum FirmwareUpdateStateEnum {
	FWUP_STATE_INIT,
	FWUP_STATE_SEND_START,
	FWUP_STATE_WAIT_START_ACK,
	FWUP_STATE_RECV_START_ACK,
	FWUP_STATE_STARTED,
	FWUP_STATE_SEND_FILE_CONTENT,
	FWUP_STATE_COMPLETED_WITH_ERROR,
	FWUP_STATE_COMPLETED_WITHOUT_ERROR,
	FWUP_STATE_COMPLETED
}
